class_name CoreEnums
extends RefCounted

enum ExecutionStatusCode {
	# 0-9: Success States
	SUCCESS = 0,
	SUCCESS_NOOP = 1,

	# 10-19: Framing & Protocol Failures
	REJECTED_INVALID_ENVELOPE = 10,
	REJECTED_STALE_TICK = 11,
	REJECTED_RATE_LIMITED = 12,

	# 20-39: Domain Preconditions & Availability
	REJECTED_PRECONDITION = 20,
	REJECTED_UNAUTHORIZED = 21,
	REJECTED_OUT_OF_BOUNDS = 22,
	REJECTED_OUT_OF_RANGE = 23,
	REJECTED_INSUFFICIENT_FUNDS = 24,
	REJECTED_CAPACITY_FULL = 25,

	# 40-59: Concurrency, Locks & Identity
	REJECTED_TARGET_LOCKED = 40,
	ABORTED_TARGET_INVALID = 41,
	ABORTED_TARGET_DISPOSED = 42,
	ABORTED_ACTOR_INCAPACITATED = 43,

	# 60+: Catastrophic Engine Failures
	FAILED_INTERNAL_ERROR = 60
}

enum ExecutionPriority {
	CRITICAL_SYSTEM = 0,
	STATE_CORRECTION = 1,
	INPUT_DIRECT = 2,
	AGENT_DECISION = 3,
	DEFERRED_CLEANUP = 4
}

enum EntityLifecycleState {
	UNINITIALIZED = 0,
	SPAWNING = 1,
	ACTIVE = 2,
	SUSPENDED = 3,
	DISPOSED = 4
}

enum StateMutationType {
	CREATE = 0,
	UPDATE = 1,
	DELETE = 2,
	PATCH = 3
}

enum AttributeOperationType {
	FLAT_ADDITION = 0,
	PERCENTAGE_ADDITIVE = 1,
	PERCENTAGE_MULTIPLICATIVE = 2,
	SET_OVERRIDE = 3,
	CLAMP_MIN_MAX = 4
}

enum SpatialDistanceMetric {
	MANHATTAN = 0,
	CHEBYSHEV = 1,
	EUCLIDEAN = 2,
	HEXAGONAL = 3
}

enum TraversalMode {
	DISCRETE_STEP = 0,
	CONTINUOUS_VECTOR = 1,
	INSTANT_TELEPORT = 2,
	CONTAINER_TRANSFER = 3
}

enum ReservationClaimType {
	EXCLUSIVE_WRITE = 0,
	SHARED_READ = 1,
	PRIORITY_PREEMPT = 2
}

enum TargetSelectionType {
	NONE = 0,
	ENTITY = 1,
	COORDINATE = 2,
	VOLUME = 3,
	CONTAINER = 4
}
