class_name CoreEnums
extends RefCounted

enum ExecutionStatusCode {
	SUCCESS = 0,
	ACCEPTED = 1,
	REJECTED_INVALID_ENVELOPE = 10,
	REJECTED_UNAUTHORIZED = 11,
	REJECTED_OUT_OF_BOUNDS = 12,
	REJECTED_TARGET_LOCKED = 20,
	REJECTED_TARGET_MISSING = 21,
	REJECTED_INSUFFICIENT_BALANCE = 22,
	REJECTED_STATE_MISMATCH = 23,
	REJECTED_TIMEOUT = 24,
	REJECTED_UNKNOWN = 25,
	ERROR_SYSTEM_FAULT = 40,
	ERROR_MISSING_VALIDATOR = 41,
	ERROR_MISSING_EXECUTOR = 42,
	ERROR_DOMAIN_CRASH = 43,
	ABORTED = 60
}

enum ExecutionPriority {
	CRITICAL_SYSTEM = 0,
	STATE_CORRECTION = 1,
	INPUT_DIRECT = 2,
	AGENT_DECISION = 3,
	DEFERRED_CLEANUP = 4
}

enum EntityLifecycleState {
	UNINITIALIZED = 0,
	SPAWNING = 1,
	ACTIVE = 2,
	SUSPENDED = 3,
	DISPOSED = 4
}

enum StateMutationType {
	CREATE = 0,
	UPDATE = 1,
	DELETE = 2,
	PATCH = 3
}

enum AttributeOperationType {
	FLAT_ADDITION = 0,
	PERCENTAGE_ADDITIVE = 1,
	PERCENTAGE_MULTIPLICATIVE = 2,
	SET_OVERRIDE = 3,
	CLAMP_MIN_MAX = 4
}

enum SpatialDistanceMetric {
	MANHATTAN = 0,
	CHEBYSHEV = 1,
	EUCLIDEAN = 2,
	HEXAGONAL = 3
}

enum TraversalMode {
	DISCRETE_STEP = 0,
	CONTINUOUS_VECTOR = 1,
	INSTANT_TELEPORT = 2,
	CONTAINER_TRANSFER = 3
}

enum ReservationClaimType {
	EXCLUSIVE_WRITE = 0,
	SHARED_READ = 1,
	PRIORITY_PREEMPT = 2
}

enum TargetSelectionType {
	NONE = 0,
	ENTITY = 1,
	COORDINATE = 2,
	VOLUME = 3,
	CONTAINER = 4
}
